### ISSUE TITLE
Please Add Steps For Building On Windows

### ISSUE THREAD

**Issue by SwiftGodDev** [utk003/Chess-AI#1]
Hi @utk003, can you please mention how to setup the GLFW, GLEW, GSL, GLM, stb libraries with Visual Studio.

**Comment by utk003** [comment]
Hi @SwiftGodDev, I did not add an explicit build guide for Windows, as the program itself has not been testing on any Windows machines. However, you can still build the project by getting all of the necessary dependencies.

All of the dependencies for this project are publicly available and [linked in the project readme](https://github.com/utk003/Chess-AI#additional-build-information). For GLFW, GLEW, GSL, and GLM, you can get the necessary header files from the library sites, and you can either download the binaries or build them yourself. For stb, the library is header-only, and the necessary header files have been included in the [libraries/include](https://github.com/utk003/Chess-AI/tree/master/libraries/include) folder.

Once you have the dependencies, just add any additional file/directory paths to the [CMake file](https://github.com/utk003/Chess-AI/blob/master/CMakeLists.txt) (if it doesn't automatically find the paths itself), and build the project just like any other C++ project. I am not too familiar with Visual Studio specifically, but you should be able to find more information for it from their documentation site. [Here](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-160) is the documentation I found for using CMake with Visual Studio.
